---
- name: Create monitoring namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ monitoring_namespace }}"
  become: true
  become_user: "{{ minikube_user }}"

- name: Render Prometheus values
  ansible.builtin.template:
    src: prometheus-values.yaml.j2
    dest: /tmp/prometheus-values.yaml
    mode: "0600"

- name: Install Prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: false
    values_files:
      - /tmp/prometheus-values.yaml
    wait: true
    wait_timeout: 10m
    state: present
  become: true
  become_user: "{{ minikube_user }}"

- name: Render Grafana values
  ansible.builtin.template:
    src: grafana-values.yaml.j2
    dest: /tmp/grafana-values.yaml
    mode: "0600"

- name: Install Grafana
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: "{{ monitoring_namespace }}"
    create_namespace: false
    values_files:
      - /tmp/grafana-values.yaml
    wait: true
    wait_timeout: 10m
    state: present
  become: true
  become_user: "{{ minikube_user }}"
