minikube_version: "v1.33.1"
kubernetes_version: "v1.30.0"
kubernetes_apt_minor: "{{ kubernetes_version | regex_replace('^v?([0-9]+\\.[0-9]+).*', 'v\\1') }}"
binary_arch_map:
  x86_64: amd64
  aarch64: arm64
  arm64: arm64
  amd64: amd64
binary_arch: "{{ binary_arch_map[ansible_architecture] | default(ansible_architecture) }}"
minikube_driver: "docker"
minikube_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
minikube_cpus: "4"
minikube_memory: "2200"
minikube_disk_size: "30g"
helm_version: "v3.15.3"
istio_version: "1.22.3"
harbor_namespace: "harbor"
harbor_chart_version: "1.15.0"
demo_namespace: "demo"
harbor_host: "harbor.localtest.me"
demo_host: "demo.localtest.me"
harbor_admin_password: "Harbor12345"
repo_root: "{{ remote_repo_dir }}"
kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
monitoring_namespace: "monitoring"
grafana_admin_password: "admin"
remote_repo_dir: "/home/{{ minikube_user }}/cloud_master_devops_task"
