apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-abort-component
  namespace: demo
spec:
  hosts: ["httpbin.demo.svc.cluster.local"]
  http:
  - fault:
      abort:
        percentage: {value: 40}
        httpStatus: 500
    route:
    - destination:
        host: httpbin.demo.svc.cluster.local
        port: {number: 8000}
